### ISSUE TITLE
The response is incomplete

### ISSUE THREAD

**Issue by mrosenfelddespegar** [langjt/node-http-proxy-json#10]
I am using node-http-proxy-json to modify the response after proxying the request. 
The problem I am experiencing is that sometimes the response is incomplete, and sometimes complete. 

I looks like the response is given to the client before executing "modifyResponse".

Any ideas?

**Comment by langjt** [comment]
@mrosenfelddespegar Can you give an example? For example, send demo code to my email.

**Comment by mrosenfelddespegar** [comment]
@langjt I've just sent you an email. Thanks!
