### ISSUE TITLE
Response break if write more "text" / "attributes" to the body

### ISSUE THREAD

**Issue by iroy2000** [langjt/node-http-proxy-json#2]
Thanks for creating this package.  

We have problem that the json response got cut off when you put in more than one attributes.  ( might be because of content length ) ?

It is working when you add one value, but seems like it is broken when you add more than one value

**If one value as in example**

```
    modifyResponse(res, proxyRes.headers['content-encoding'], function (body) {
        if (body) {
            // modify some information
            body.version = 2;
        }
        return body;
    });
```

**Result --> It return as an full JSON**
<img width="136" alt="screen shot 2016-08-08 at 6 20 15 pm" src="https://cloud.githubusercontent.com/assets/487520/17501565/d9ce6766-5d94-11e6-92bd-60cdd3f704b4.png">

---

**If more than one value**

```
    modifyResponse(res, proxyRes.headers['content-encoding'], function (body) {
      if (body) {
        // modify some information
        // just adding one more attribute here below
        body.version = 2;
        body.age = 2;
      }
      return body;
    });
```

**Result -->  It actually cut off, NOT a valid JSON**
<img width="508" alt="screen shot 2016-08-08 at 6 18 50 pm" src="https://cloud.githubusercontent.com/assets/487520/17501534/9935837e-5d94-11e6-9640-7d7aa7592bbd.png">

**Comment by iroy2000** [comment]
Ok, just answering my question, delete the content length will work ... 

```
    delete proxyRes.headers['content-length'];
```

**Comment by gogson** [comment]
Well it works but deleting the Content-Length header will switch the response to 
`Transfer-Encoding: chunked` mode.

It's useful for dynamic content (streaming something for example) but a solution with the `Content-Length` header would be better.

**Comment by art1c0** [comment]
the same issue here - after modifying the response it fails... content-length header is not changing when the response is changed - this is the problem... could you please fix it or tell how to overcome the issue?
